name: Sync Tutorials Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  sync-tutorials:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Frontend Repo
      uses: actions/checkout@v2
      with:
        path: 'frontend'
        fetch-depth: 0  # 确保能获取所有分支和标签

    - name: Configure safe directory
      run: git config --global --add safe.directory ${{ github.workspace }}/frontend
      working-directory: ./frontend  # 确保在正确的目录执行

    - name: List directory contents
      run: ls -la
      working-directory: ./frontend

    - name: Sync WTF Ethers Tutorials
      run: |
        git clone https://github.com/WTFAcademy/WTF-Ethers.git
        cp -r WTF-Ethers/0{1..9}_* ./docs/ethers-101/
        cp -r WTF-Ethers/10_* ./docs/ethers-101/
        rm -rf WTF-Ethers
      working-directory: ./frontend  # 确保在正确的目录执行

    - name: Prepare for pull request
      run: |
        git config --local --get remote.origin.url
      working-directory: ./frontend  # 显式指定 Git 操作目录

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GH_TOKEN }}  # 确保使用正确的访问令牌
        commit-message: Update tutorials
        title: "Update Tutorials"
        body: "This is an automated PR to update tutorials"
        branch: "update-tutorials-${{ github.run_id }}"
        base: "main"
        labels: "automated pr"
