name: Sync Tutorials

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  sync-tutorials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Current Directory
        run: ls -al

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Debug Path
        run: ls -al frontend/scripts/sync

      - name: Run Sync Script
        working-directory: frontend/scripts/sync
        run: |
          chmod +x sync.sh
          ./sync.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}  # 确保使用正确的访问令牌
          commit-message: Update tutorials
          title: "Update Tutorials"
          body: |
            This is an automated PR to update tutorials.
            $(cat changes.txt)
          branch: "update-tutorials-${{ github.run_id }}"
          base: "main"
          labels: "automated pr"
