name: Sync Tutorials New

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  sync-tutorials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Sync Documentation
        run: |
          chmod +x sync-docs.sh
          ./sync-docs.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}  # 确保使用正确的访问令牌
          commit-message: Update tutorials
          title: "Update Tutorials"
          body: |
            This is an automated PR to update tutorials.
            ${{
              steps.sync-tutorials.outputs.changes
            }}
          branch: "update-tutorials-${{ github.run_id }}"
          base: "main"
          labels: "automated pr"
